#!/usr/bin/env node

'use strict';

var webpack = require('webpack');
var fs = require('fs');
var path = require('path');
var ora     = require('ora');
var febs     = require('febs');
const TerserPlugin = require('terser-webpack-plugin');
var nodeExternals = require('webpack-node-externals');

var spinner = ora('Build... ');

exports.run = function (workdir, bundleAll) {
  console.log(workdir)
  
  function resolveDistPath(...paths) {
    return path.join(workdir, '_dist', ...paths)
  }

  function resolveSrcPath(...paths) {
    return path.join(workdir, ...paths);
  }


  febs.file.dirRemoveRecursive(resolveDistPath('resource'));
  febs.file.dirAssure(resolveDistPath('resource'));
  febs.file.dirCopy(resolveSrcPath('resource'), resolveDistPath('resource'));
  febs.file.fileRemove(resolveDistPath('package.json'));
  febs.file.fileCopy(resolveSrcPath('package.json'), resolveDistPath('package.json'));
  febs.file.fileRemove(resolveDistPath('readme.md'));
  febs.file.fileCopy(resolveSrcPath('readme.md'), resolveDistPath('readme.md'));
  febs.file.dirAssure(resolveDistPath('libs'));

  var nodeModules = {};
  fs.readdirSync('node_modules')
    .filter(function (x) {
      return ['.bin'].indexOf(x) === -1;
    })
    .forEach(function (mod) {
      nodeModules[mod] = 'commonjs ' + mod;
    });

  var cfg = {
    mode: "production",
    devtool: "hidden-source-map",
    entry: [
      '@babel/polyfill', resolveSrcPath('src/main.ts')
    ],
    output: {
      path: resolveDistPath(),
      filename: 'libs/libs.js'
    },
    resolve: {
      // Add `.ts` and `.tsx` as a resolvable extension.
      extensions: ['.ts', '.tsx', '.js'],
      alias: {
        '@': resolveSrcPath("src"),
      }
    },
    target: 'node',
    externals: [nodeExternals({
      allowlist: bundleAll ? /.*/ : [
        '@babel/polyfill',
        /core-js\/.*/,
      ]
    })],
    optimization: {
      minimize: true,
      minimizer: [new TerserPlugin({
        terserOptions: {
          keep_classnames: true,
          keep_fnames: true,
        },
      })],
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          use: 'ts-loader',
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: 'babel-loader',
        },
      ]
    }
  }

  spinner.start();
  let compiler = webpack(cfg);

  compiler.run(function (err, stats) {
    if (err) {
      console.error(err);
      process.exit(0);
    }

    console.log(stats.toString({
      colors: true
    }));
    spinner.stop();

    febs.file.fileRemove(resolveDistPath('libs/app.js'));
    febs.file.fileRemove(resolveDistPath('libs/app-cron.js'));
    febs.file.fileCopy(path.join(__dirname, 'app.js'), resolveDistPath('libs/app.js'));
    febs.file.fileCopy(path.join(__dirname, 'app-cron.js'), resolveDistPath('libs/app-cron.js'));
  });
}